name: NanobionicsTestVirusDesktop

on:
  push:
    tags:
      - '*'

jobs:

  build:
  
    runs-on: windows-latest
    env:
      MSBUILD_PATH: C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\

    steps:
    - run: echo $Env:MSBUILD_PATH | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append  

    - uses: actions/checkout@v2
    
    - name: Version
      uses: mad9000/actions-find-and-replace-string@1
      id: release_version
      with:
        source: ${{ github.ref }}
        find: 'refs/tags/' 
        replace: ''

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v1.0.2

    # Restore the application to populate the obj folder with RuntimeIdentifiers
    - name: Build with dotnet
      run: dotnet build $Env:GITHUB_WORKSPACE\NanobionicsTestVirusDesktop --configuration Release --output bin\Release -nowarn:CS0168,CS1998
      
    # Installer app
    - name: Build Installer
      #run: devenv $Env:GITHUB_WORKSPACE\NanobionicsTestVirusInstaller\NanobionicsTestVirusInstaller.vdproj /build Release
      run: ./build-install.ps1
      
    # Upload artifacts
    - name: Upload Artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: NanobionicsTestVirus_${{ steps.release_version.outputs.value }}
        path: bin\Release
        retention-days: 90
    
    - name: Set message
      #run: echo "::set-env name=MESSAGE::$(git tag -l -n10 --points-at HEAD --format='%(contents:subject)')"
      run: |
        chcp 65001 #set code page to utf-8
        echo ("MESSAGE=" + $(git tag -l -n10 --points-at HEAD --format='%(contents:subject)')) >> $env:GITHUB_ENV
    
    - name: Upload binaries to release
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: bin\Release\NanobionicsTestVirusInstaller.msi
        asset_name: NanobionicsTestVirusInstaller-x64.msi
        tag: ${{ github.ref }}
        overwrite: true
        body: ${env:MESSAGE}
        
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.0
      with:
        name: NanobionicsTestVirus_${{ steps.release_version.outputs.value }}
        path: bin\Release